### PR TITLE
[wasm] Unlock FTS-related code on WASI

### LINKED ISSUE #1785: `FileManager.removeItem` can't remove a non-empty directory on WASI
### Description

Foundation's `FileManager.removeItem` can remove a directory that has child files and directories, but it can't on WASI.

### Steps to reproduce

1. Create a new project and set to use main-snapshot-2026-02-24

    ```shell
    mkdir wasi_removeitem_demo
    cd wasi_removeitem_demo
    swift package init --type executable
    git init
    swiftly install --use main-snapshot-2026-02-24
    ```

2. Edit Sources/wasi-removeitem-demo/wasi_removeitem_demo.swift

    ```swift
    import Foundation
    
    @main
    struct wasi_removeitem_demo {
        static func main() throws {
            try FileManager.default.createDirectory(atPath: "dir", withIntermediateDirectories: false)
            guard FileManager.default.createFile(atPath: "dir/file", contents: nil) else {
                fatalError("failed to create dir/file")
            }
            try FileManager.default.removeItem(atPath: "dir")
            print("success")
        }
    }
    ```

3. Build it

    ```shell
    swift sdk install https://download.swift.org/development/wasm-sdk/swift-DEVELOPMENT-SNAPSHOT-2026-02-24-a/swift-DEVELOPMENT-SNAPSHOT-2026-02-24-a_wasm.artifactbundle.tar.gz --checksum dc6e2fc24fb6cd7c7b72ef8d61dbfc3577bc1e360f33d410aebeda8974f1d02f
    swift run --swift-sdk "$(swiftc -print-target-info | jq -r '.swiftCompilerTag')_wasm"
    ```

### Actual behavior

```console
$ swift run --swift-sdk "$(swiftc -print-target-info | jq -r '.swiftCompilerTag')_wasm"
Building for debugging...
[7/7] Linking wasi-removeitem-demo.wasm
Build of product 'wasi-removeitem-demo' complete! (0.46s)
Swift/ErrorType.swift:254: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=3328 "The requested operation is not supported."UserInfo={NSFilePath=dir, NSURL=dir -- file:///}
Error: Trap: unreachable
    0: (0x0000000c35af97d0) $ss17_assertionFailure__4file4line5flagss5NeverOs12StaticStringV_SSAHSus6UInt32VtF
    1: (0x0000000c35a908a8) swift_errorInMain
    2: (0x0000000c397eccc0) main
    3: (0x0000000c35a340c0) __main_void
    4: (0x000000016cf76a58) _start
    5: (0x0000000100000003) unknown
```

And, `dir` and `dir/file` remain.

### Expected behavior

It can successfully run like other platforms.

```console
$ swift run
Building for debugging...
[7/7] Applying wasi-removeitem-demo
Build of product 'wasi-removeitem-demo' complete! (0.41s)
success
```

### Environment

```console
$ swiftc --version
Apple Swift version 6.3-dev (LLVM 9a422f962b2edaa, Swift 21dc148496a3953)
Target: arm64-apple-macosx26.0
Build config: +assertions
$ sw_vers
ProductName:            macOS
ProductVersion:         26.3
BuildVersion:           25D125
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kkebo**
fixes #1785 

### Motivation:

- #1785

### Modifications:

Similar to https://github.com/swiftlang/swift-corelibs-foundation/pull/5418, I have unlocked all FTS-related code on WASI.

### Result:

`FileManager.removeItem` can now remove a non-empty directory.

### Testing:

Running `swift build --swift-sdk "$(swiftc -print-target-info | jq -r '.swiftCompilerTag')_wasm"` on this repository succeeded.

And, I created a repository to confirm that the issue reported in #1785 has been resolved: https://github.com/kkebo/wasi-removeitem-demo.

- [Before modification](https://github.com/kkebo/wasi-removeitem-demo/commit/9257f6df50a2a768fc090ccc8fe8166207f47b96): `swift run --swift-sdk "$(swiftc -print-target-info | jq -r '.swiftCompilerTag')_wasm"` failed as described in #1785.
- [After modification](https://github.com/kkebo/wasi-removeitem-demo/commit/74eb83d396a52e0ad5b48e260fd8e41b0648787c): `swift run --swift-sdk "$(swiftc -print-target-info | jq -r '.swiftCompilerTag')_wasm"` succeeded.

### CODE REVIEW

**Comment by kkebo** [comment]
@kateinoigakukun If possible, I'd appreciate it if you could check if there are any other areas that need unlocking.

**Comment by kateinoigakukun** [comment]
@swift-ci test

File: Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift [hunk 1]
```diff
@@ -483,5 +480,3 @@ struct _POSIXDirectoryContentsSequence: Sequence {
         Iterator(path: path, appendSlashForDirectory: appendSlashForDirectory, prefix: prefix)
     }
 }
-
-#endif
```
Comment (kkebo) [inline Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift:487]: This is a mistake.

Comment (kkebo) [reply Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift:487]: Fixed. https://github.com/swiftlang/swift-foundation/compare/eeb26b892edd7a0cca49c11b7821490e0525bebd..511a908aa9831d90a38730dbc43e743e1f214448

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by jmschonfeld** [comment]
@kkebo thanks! I know we don't currently run our unit tests on WASI in CI, but do we know if this change is covered by a unit test? I suspect that either we had a unit test for it that previously failed, or we don't have a unit test for this situation. Even if we don't run WASI tests in CI, we should make sure it's covered so if it's the latter it'd be great to add a unit test, but if we have one that already covers this then we're good to go

**Comment by jmschonfeld** [comment]
Confirmed we do have existing tests for all of these
